- alias: Ab ins Bett
  trigger:
     platform: time
     at: "23:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
  action:
    service: scene.turn_on
    entity_id: scene.nachtruhe
- alias: Licht zu Sonnenuntergang
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    service: scene.turn_on
    entity_id: scene.romantic
